var searchData=
[
  ['babyrestriction_0',['BabyRestriction',['../class_pokemon_unity_1_1_baby_restriction.cshtml',1,'PokemonUnity']]],
  ['badgedata_1',['BadgeData',['../struct_pokemon_unity_1_1_character_1_1_badge_data.cshtml',1,'PokemonUnity::Character']]],
  ['banneditemrestriction_2',['BannedItemRestriction',['../class_pokemon_unity_1_1_banned_item_restriction.cshtml',1,'PokemonUnity']]],
  ['bannedspeciesrestriction_3',['BannedSpeciesRestriction',['../class_pokemon_unity_1_1_banned_species_restriction.cshtml',1,'PokemonUnity']]],
  ['battle_4',['Battle',['../class_pokemon_unity_1_1_combat_1_1_battle.cshtml',1,'PokemonUnity::Combat']]],
  ['battleabortedexception_5',['BattleAbortedException',['../class_pokemon_unity_1_1_combat_1_1_battle_aborted_exception.cshtml',1,'PokemonUnity::Combat']]],
  ['battlearena_6',['BattleArena',['../class_pokemon_unity_1_1_battle_arena.cshtml',1,'PokemonUnity']]],
  ['battlepalace_7',['BattlePalace',['../class_pokemon_unity_1_1_battle_palace.cshtml',1,'PokemonUnity']]],
  ['battler_8',['Battler',['../class_pokemon_unity_1_1_combat_1_1_effects_1_1_battler.cshtml',1,'PokemonUnity::Combat::Effects']]],
  ['battlerule_9',['BattleRule',['../class_pokemon_unity_1_1_battle_rule.cshtml',1,'PokemonUnity']]],
  ['battletower_10',['BattleTower',['../class_pokemon_unity_1_1_battle_tower.cshtml',1,'PokemonUnity']]],
  ['battletype_11',['BattleType',['../class_pokemon_unity_1_1_battle_type.cshtml',1,'PokemonUnity']]],
  ['battleuseonbattlereventargs_12',['BattleUseOnBattlerEventArgs',['../class_pokemon_unity_1_1_battle_use_on_battler_event_args.cshtml',1,'PokemonUnity']]],
  ['battleuseonpokemoneventargs_13',['BattleUseOnPokemonEventArgs',['../class_pokemon_unity_1_1_battle_use_on_pokemon_event_args.cshtml',1,'PokemonUnity']]],
  ['berrydata_14',['BerryData',['../struct_pokemon_unity_1_1_inventory_1_1_berry_data.cshtml',1,'PokemonUnity::Inventory']]],
  ['buttoneventargs_15',['ButtonEventArgs',['../class_pokemon_unity_1_1_input_1_1_button_event_args.cshtml',1,'PokemonUnity::Input']]]
];
